version: "3"

services: 
  laptop_setup:
    image: ghcr.io/droid-dataset/droid_laptop:panda
    environment:
      DISPLAY: ${DISPLAY}
      XAUTHORITY: ${DOCKER_XAUTH}
      ROBOT_TYPE: panda
      LIBFRANKA_VERSION: 0.9.0
      NUC_IP: 192.168.10.4
      ROBOT_IP: 192.168.10.100
      LAPTOP_IP: 192.168.10.4
      NVIDIA_VISIBLE_DEVICES: all
      ANDROID_ADB_SERVER_ADDRESS: host.docker.internal
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${DOCKER_XAUTH}:${DOCKER_XAUTH}
      - /home/panda/liris_droid/droid/misc/parameters.py:/app/droid/misc/parameters.py
      - /home/panda/liris_droid/droid/calibration/calibration_info.json:/app/droid/calibration/calibration_info.json
      - /home/panda/liris_droid/data:/app/data
      - /home/panda/liris_droid/cache:/app/cache
      - /home/panda/liris_droid/checkpoints:/app/checkpoints
    build: 
      context: ../../
      dockerfile: .docker/laptop/Dockerfile.laptop
      args:
        ROOT_DIR: /home/panda/liris_droid
        ROBOT_TYPE: panda
        NUC_IP: 192.168.10.4
        ROBOT_IP: 192.168.10.100
    devices:
      - "/dev:/dev"
    runtime: nvidia
    privileged: true
    network_mode: "host"
    command: python /app/scripts/main.py
