defaults:
  - algo: openvla

language_conditioned: true
exp_name: policy_test
save_data: false
seed: 0
policy_logdir: test
task: ""
layout_id: None
model_id: 50
camera_kwargs: {}
data_processing_kwargs:
  timestep_filtering_kwargs: {}
  image_transform_kwargs: {}